provider:
  name: chamber-provider

devices:
  - id: tempctl0
    type: tempctl
    initial_temp: 22.0

simulation:
  mode: sim
  tick_rate_hz: 10.0
  physics_config: multi-provider-extrusion.yaml
  ambient_temp_c: 22.0
